# Generated by Django 5.1.5 on 2025-01-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_cell_is_occupied_alter_order_end_storage_and_more'),
        ('storage', '0003_alter_order_end_storage_alter_order_start_storage'),
    ]

    operations = [
    ]
