# Generated by Django 5.1.5 on 2025-01-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_merge_20250130_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='message_count',
        ),
    ]
