# Generated by Django 5.1.5 on 2025-01-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_remove_order_message_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
