# Generated by Django 5.1.5 on 2025-01-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_remove_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField()),
            ],
        ),
    ]
